[directory]
style = "cyan"

[git_branch]
symbol = "🌱  "
style = "bold green"

[git_status]
style = "yellow"
modified = "M"
stashed = "S"

[ruby]
style = "red"

[character]
error_symbol = "✗"
use_symbol_for_status = true

[memory_usage]
disabled = false
show_percentage = true

[cmd_duration]
disabled = true
